BEGIN;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS domestic_beta NUMERIC(12,6) NULL;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS global_beta NUMERIC(12,6) NULL;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS beta_collected_at TIMESTAMP WITHOUT TIME ZONE NULL;

COMMIT;
